### ISSUE TITLE
Faire migrer défis EIG3 de la page candidats à la page défis

### ISSUE THREAD

**Issue by MathildeBras** [entrepreneur-interet-general/site-eig#108]
Et ouvrir des fiches profils par lauréats pour les lier entre elles ?
En faire un atelier github pour une partie de l'équipe qui débuterait ? (Victor, Gabriele, Mathilde H) ?

**Comment by milkosofi** [comment]
Les défis sont migrées. Les fiches vont arriver.

**Comment by AntoineAugusti** [comment]
Fait depuis
