### ISSUE TITLE
Faire tourner en local

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/site-eig#118]
Tu pourrais rajouter des instructions pour exécuter en local ?

Je me suis contenté de
```
bundle install
jekyll build --watch --incremental
```

mais les URLs restent celles de la production.

**Comment by bzg** [comment]
Fait dans 2e901dc - merci !

PS: Je gère le site jusqu'au 15 janvier mais n'hésite pas à prendre les choses en main avant et à ouvrir des issues comme celle-ci pour les questions.
