### ISSUE TITLE
Changer hastag dans le lien de partage Twitter

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/site-eig#119]
Passer (automatiquement ?) de #eig2018 à #eig2019.

https://github.com/entrepreneur-interet-general/site-
eig/blob/dd8553e7c1a8b8c48b14158bb53bcb12ed7fa627/_includes/share-bar.html#L4

**Comment by bzg** [comment]
Bonne idée! Peut-être utiliser le milestone "v3" plutôt que le label "eig3"?
