### ISSUE TITLE
Carroussel page accueil sur mobile

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/site-eig#123]
Le texte et le bouton ne sont pas responsive
![](https://puu.sh/CyxSC/9ea3776211.png)

**Comment by milkosofi** [comment]
As-tu une idée de pourquoi ? Est-ce que je peux faire quelque chose pour régler cette issue ?

**Comment by AntoineAugusti** [comment]
C'est un problème de CSS. Je m'en chargerai un jour. À voir si on change cette phrase un jour.
