### ISSUE TITLE
Vérifier le flux RSS

### ISSUE THREAD

**Issue by jbledevehat** [entrepreneur-interet-general/site-eig#125]
https://entrepreneur-interet-general.etalab.gouv.fr/feed.xml

**Comment by bzg** [comment]
Le flux fonctionne correctement chez moi, il permet de suivre et de lire entièrement les publications du blog EIG.

**Comment by AntoineAugusti** [comment]
En chargeant dans Chrome, pas de problème. Surement un rendu bizarre par Safari quand on avait regardé
