### ISSUE TITLE
Synchronisation des réseaux sociaux avec les questionnaires

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/site-eig#129]
Suite à l'envoi de questions aux EIG, nous avons récolté des infos sur leurs réseaux sociaux (LinkedIn / Twitter / GitHub). S'assurer que toutes les fiches des EIG 2019 sont bien à jour avec les dernières infos récoltées.

@guenolec, je nous assigne. Je t'expliquerai comment faire ça.

**Comment by AntoineAugusti** [comment]
Du coup @guenolec tu confirmes que l'on peut fermer cette issue pour le moment suite à tes commits ce jour ?

**Comment by guenolec** [comment]
Oui j'ai inclus toutes les infos fournis par les EIG 3 dans le formulaire que tu avais mis en ligne
