### ISSUE TITLE
Frise déroulé du programme

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/site-eig#130]
Sur la page https://entrepreneur-interet-general.etalab.gouv.fr/presentation.html on présente une frise avec les différentes phases du programme EIG.

Actuellement, on devrait être au point 3.  L’image est la suivante https://entrepreneur-interet-general.etalab.gouv.fr/img/Frise-programme.png et je ne sais pas qui l’a réalisée.

**Comment by MathildeBras** [comment]
Poke @Sophie !
J'ai retrouvé un png sur le serveur mais pas le visuel sans surlignage du cadre.
Mathilde

Le Mercredi 6 Février 2019 12:29 CET, Antoine Augusti <notifications@github.com> a écrit:
 
Sur la page https://entrepreneur-interet-general.etalab.gouv.fr/presentation.html on présente une frise avec les différentes phases du programme EIG.
Actuellement, on devrait être au point 3. L’image est la suivante https://entrepreneur-interet-general.etalab.gouv.fr/img/Frise-programme.png et je ne sais pas qui l’a réalisée.

**Comment by milkosofi** [comment]
Salut Antoine, 

C'est bien moi qui l'ai réalisé. Merci pour l'issue.

Sophie

 
Le Mercredi 6 Février 2019 14:53 CET, Antoine Augusti <notifications@github.com> a écrit:

**Comment by milkosofi** [comment]
J'ai ajouté une version mise à jour de la frise.
