### ISSUE TITLE
Remplacer le logo avec le nouveau nom du programme

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/site-eig#136]
Arrêt du point médian et passage au pluriel

**Comment by AntoineAugusti** [comment]
Done in https://github.com/entrepreneur-interet-general/site-eig/commit/765b5e7cb0a1424d6d5f0955653ea9f7f5000346?short_path=479e250#diff-479e250822824c1a60b95c1f8c229369 and https://github.com/entrepreneur-interet-general/site-eig/commit/b65aa16b4eae518005a55db72b9da90242bee8ac by @milkosofi

**Comment by milkosofi** [comment]
Salut, j'ai l'impression d'avoir été assign après la fermeture de l'issue ; il y a une raison ?

**Comment by AntoineAugusti** [comment]
C'est bien le cas. Si jamais quelqu'un parcourt l'historique des issues, il saura que c'est toi qui est en charge de ces sujets

**Comment by milkosofi** [comment]
OK, merci !
