### ISSUE TITLE
Menu non fonctionnel Safari iOS iPhone 7

### ISSUE THREAD

**Issue by wojteksitarz** [entrepreneur-interet-general/site-eig#137]
Sur mon IPhone, iOS 12.1.4, certains boutons du menu du site EIG (Progamme, Projets, Communauté) ne marchent pas sous Safari. Impossible du coup d’acceder au trombino sur mobile par exemple.

**Comment by milkosofi** [comment]
Salut @wojteksitarz ! Les boutons qui ne fonctionnent pas sont seulement programme, projets et communauté ou y en a-t-il d'autres ?

**Comment by wojteksitarz** [comment]
C’était il y a plus d’un an^^ le site à pas mal évolué depuis. je viens de regarder à nouveau et tout semble bien marcher!:)

**Comment by milkosofi** [comment]
Merci pour le retour ! Je ferme donc l'issue :)
