### ISSUE TITLE
Photo manquante : Laurent Toustou

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/site-eig#138]
Mentor DataReg https://entrepreneur-interet-general.etalab.gouv.fr/defis/2019/datareg.html

**Comment by AntoineAugusti** [comment]
@guenolec ou @milkosofi, pouvez-vous vous en charger ?

Il y a une miniature existante https://github.com/entrepreneur-interet-general/site-eig/blob/master/img/communaute/miniatures/laurent-toustou.jpg mais pas de grande photo

**Comment by milkosofi** [comment]
J'ai ajouté la photo.
