### ISSUE TITLE
Remplacement logo du programme dans le footer

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/site-eig#144]
Le logo dans le pied de page est l'ancien
![](https://puu.sh/D54je/e03314ad05.png)

**Comment by milkosofi** [comment]
Done ; merci.

**Comment by AntoineAugusti** [comment]
Fait dans https://github.com/entrepreneur-interet-general/site-eig/commit/f10a9dd28d02a6432f49594c97aa40d4246cbf4e
