### ISSUE TITLE
Activer le carrousel de la page d'accueil 

### ISSUE THREAD

**Issue by milkosofi** [entrepreneur-interet-general/site-eig#146]
L'image de la page d'accueil est intégrée dans un carousel que l'on a figé. Pourrais-tu le réactiver ? J'aimerais tester de mettre des informations plus récentes dans le carousel.

**Comment by AntoineAugusti** [comment]
Hello Sophie,

Tu peux regarder la PR https://github.com/entrepreneur-interet-general/site-eig/pull/149 et en particulier la preview associée pour voir ce que ça donne et où il faut modifier les choses.

**Comment by AntoineAugusti** [comment]
Si nécessaire, il y a un exemple de code dans la PR.
