### ISSUE TITLE
Mettre une vidéo dans le carousel de la page d'accueil

### ISSUE THREAD

**Issue by milkosofi** [entrepreneur-interet-general/site-eig#147]
Est-il possible d'intégrer une vidéo dans le carousel de la page d'accueil ? Cela pourrait être un bon endroit pour publier la vidéo du bootcamp.

**Comment by AntoineAugusti** [comment]
Hello,

Je suis contre mettre une vidéo aussi tôt dans la navigation du site web. Je trouve ça très intrusif.

**Comment by milkosofi** [comment]
Ton avis a été indirectement pris en compte : la vidéo du bootcamp a été ajoutée dans la page de présentation du programme :) En lien avec #174
