### ISSUE TITLE
Créer une page sans la publier sur le site

### ISSUE THREAD

**Issue by milkosofi** [entrepreneur-interet-general/site-eig#148]
Est-il possible de créer une page dans le github sans pour autant l'afficher dans le site en production ? Cela pourrait nous servir à prototyper l'espace presse, sans pour autant la publier tout de suite.

**Comment by AntoineAugusti** [comment]
Hello,

Tant que la page est sur une branche, et pas sur `master`, ceci n'est pas déployé en production. C'est-à-dire que ce ne sera pas sur le site public. En revanche, il y a déjà des pages qui existent, qui ne sont pas présentes dans les menus et qui ne sont pas finies.

Je pense à https://github.com/entrepreneur-interet-general/site-eig/blob/master/presse.html, accessible en ligne https://entrepreneur-interet-general.etalab.gouv.fr/presse.html.

L'idée serait donc de travailler sur la page dans une branche, de voir ce que ça donne grâce à la prévisualisation et de merger ensuite

**Comment by milkosofi** [comment]
Ok, merci @AntoineAugusti pour les précisions.
