### ISSUE TITLE
Supprimer les "guide" dans le sous-menu de "programme"

### ISSUE THREAD

**Issue by milkosofi** [entrepreneur-interet-general/site-eig#150]
Les guides sont présentés dans la page "accompagnement". On peut donc les supprimer de la barre de menu. Comment faut-il procéder ? J'aimerais apprendre à le faire pour pouvoir modifier la barre de menu à l'avenir.

**Comment by AntoineAugusti** [comment]
Voir PR https://github.com/entrepreneur-interet-general/site-eig/pull/151. Je te laisse regarder le code et merger ensuite

**Comment by milkosofi** [comment]
C'est mergé, merci.
