### ISSUE TITLE
Problème d'affichage de la faq administration

### ISSUE THREAD

**Issue by guenolec** [entrepreneur-interet-general/site-eig#152]
https://entrepreneur-interet-general.etalab.gouv.fr/faq-administrations.html

Sur cette page dans mon navigateur (mozilla), problème d'affichage des questions réponses dans les différentes boites.
Je crois comprendre que cette page dépend de ces deux commits : 
https://github.com/entrepreneur-interet-general/site-eig/blob/master/faq-administrations.html
https://github.com/entrepreneur-interet-general/site-eig/blob/master/_data/faq-administrations.yml

Mais je ne sais pas comment agir dessus.

**Comment by AntoineAugusti** [comment]
Merci @guenolec de ta vigilance !
