### ISSUE TITLE
Projets / défis

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/site-eig#176]
Le menu fait désormais apparaître le terme de "Projets" au lieu de défis, toutefois on retrouve encore le terme de "défi" sur plusieurs pages. #167 

Abandonnons-nous le terme de défi au bénéfice de projet ?

**Comment by bzg** [comment]
Perso, je suis pour garder "défi" dans la communication sur les recrutements (de mentors et d'EIG) et "projets" dans les autres cas. "Défi" se démarque des projets classiques de l'administration.

**Comment by jbledevehat** [comment]
Je garderais le mot "défi" et utiliser le mot "projet" pour décrire un défi me conviens. Nous pouvons modifier cela si cela convient aussi @milkosofi

**Comment by AntoineAugusti** [comment]
On garde défi
