### ISSUE TITLE
Date de publication et d'écriture sur le blog EIG

### ISSUE THREAD

**Issue by guenolec** [entrepreneur-interet-general/site-eig#220]
J'ouvre une issue pour une petite question de dates : 

Quand on poste un article sur le blog EIG, la date affichée sur le blog est celle de la création du premier commit relatif à l'article. 

Exemple : l'article sur les Gobelins affiche une date de publication au 14 juin sur le site (https://entrepreneur-interet-general.etalab.gouv.fr/blog/2019/06/14/site-mobilier-national-temoignages-utilisateurs.html) mais a en réalité été publiée le 20 juin (date de merge ici : https://github.com/entrepreneur-interet-general/site-eig/pull/206)

Question : est-il possible de régler l'affichage sur le blog à la date de publication et non à la date de création du premier commit ?

**Comment by AntoineAugusti** [comment]
C'est défini par le nom du fichier, qui est actuellement 2019-06-14. Changer le nom du fichier permet de changer cette date https://github.com/entrepreneur-interet-general/site-eig/blob/master/_posts/2019-06-14-site-mobilier-national-temoignages-utilisateurs.md

**Comment by guenolec** [comment]
Sauf qu'il ne me semble pas possible de modifier le nom d'un fichier via la version en ligne de GitHub ?

**Comment by AntoineAugusti** [comment]
C'est possible https://help.github.com/en/articles/renaming-a-file

**Comment by guenolec** [comment]
C'est noté ! 
Merci :)
