### ISSUE TITLE
Réduire la largeur du texte dans les blogspots

### ISSUE THREAD

**Issue by milkosofi** [entrepreneur-interet-general/site-eig#224]
Salut ! 

Suite à un mail de Brice, nous avons eu une discussion sur la lisibilité de nos articles de blog. Il en est ressorti que les lignes étaient trop longues. Brice à compté : nous sommes à 119 caractères par ligne en moyenne alors qu'ile st recommandé d'en avoir entre 45 et 75 caractères.

@jbledevehat pourrais-tu te pencher sur le sujet et voir comment nous pourrions réduire la largeur du texte dans nos articles de blog ?

**Comment by AntoineAugusti** [comment]
Oups je n'avais pas vu cette issue avant et j'ai déjà fait une PR https://github.com/entrepreneur-interet-general/site-eig/pull/225

**Comment by milkosofi** [comment]
C'est mergé. Merci @AntoineAugusti !
