### ISSUE TITLE
Faire passer l'en-tête des menus en item du dropdown

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/site-eig#23]
Je note ce point ici, mais je pense qu'il faut plus de retours sur le sujet.  Je pense qu'il s'agit peut-être simplement de mettre l'en-tête de menu de la même couleur que le sous-menu.

**Comment by bzg** [comment]
Tentative d'implémentation de l'idée d'une même couleur (qui peut changer) quand on passe la souris sur l'en-tête et sur les sous-items : https://github.com/entrepreneur-interet-general/site-eig/commit/50b4044ef90952a46a1c0584142c24dbcc6b4512

**Comment by MathildeBras** [comment]
Ok.
Je trouve que la modif de survol est déjà pas mal.
On peut aussi faire tester à un.e inconnu.e.

Mathilde 

Le Lundi 30 Juillet 2018 20:42 CEST, Bastien <notifications@github.com> a écrit:

**Comment by milkosofi** [comment]
Salut, 

La modification de survol est une super idée. Je vais faire tester par des gens de mon entourage, ça devrait être intéressant.

Sophie

**Comment by MathildeBras** [comment]
Objectif idéal : 
- programme / projets / communauté : non cliquable
- actualité et participer : cliquable

Si impossible - deux options
- tout rendre rendre non cliquable
OU
- dupliquer certaines pages : programme (double de "notre ambition" / les projets (double de "défis") / la communauté (double de "les eig et mentors)

**Comment by bzg** [comment]
Objectif idéal implémenté dans https://github.com/entrepreneur-interet-general/site-eig/commit/b91e9103ad0948e07c3bfc74bdfb7cfdc6bc9efa

Il reste à définir vers quelle URL doit pointer l'en-tête "Actualités".

**Comment by bzg** [comment]
Fait.
