### ISSUE TITLE
Décalage sur la page d'accueil

### ISSUE THREAD

**Issue by guenolec** [entrepreneur-interet-general/site-eig#233]
Le bouton "Découvrir la promotion 3" est sur la gauche dans le carrousel principal sur la page d'accueil. Problème de CSS ? 
![image](https://user-images.githubusercontent.com/46894478/60591586-10e03200-9d9f-11e9-9ca9-eb7b9f2868e7.png)

**Comment by AntoineAugusti** [comment]
Tu te sens d'essayer de réparer ?

**Comment by guenolec** [comment]
j'ai tenté quelque chose ici : https://github.com/entrepreneur-interet-general/site-eig/pull/234

Mais je n'arrive pas à voir le deploy (problème de certificat sur netlify, le site m'affiche une erreur)

**Comment by guenolec** [comment]
Problème partiellement fixé par cette PR : https://github.com/entrepreneur-interet-general/site-eig/pull/234

Je la ferme pour l'instant, en ouvrant une autre PR sur la non-responsivité de la page d'accueil.
