### ISSUE TITLE
Ajouter les liens vers les sites personnels ou les pages linkedin pour les mentors

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/site-eig#25]
@milkosofi @MathildeBras : OK pour mettre un lien vers la page `linkedin` du mentor au lieu du site personnel quand celui-ci n'existe pas?

(Je ne suis pas pour ajouter une icone spécifique pour `linkedin`.)

**Comment by MathildeBras** [comment]
Oui OK.
 


Le Lundi 30 Juillet 2018 20:48 CEST, Bastien <notifications@github.com> a écrit:

**Comment by bzg** [comment]
Fait pour EIG1 et EIG2, pas encore EIG3.

**Comment by bzg** [comment]
@milkosofi : je fais remonter cette issue pour voir s'il y a des informations qu'on peut d'ores et déjà ajouter.

**Comment by AntoineAugusti** [comment]
Je ferme. On mettra au fur et à mesure du possible pour les mentors.
