### ISSUE TITLE
Logo écriture inclusive

### ISSUE THREAD

**Issue by oncletom** [entrepreneur-interet-general/site-eig#346]
Hello 👋

Je cherche le logo `eig.svg`, mais en version écriture inclusive.

Vous avez un lien vers ce fichier en format vectorisé ?
S'il est sur le dépôt, je ne l'ai pas vu.

Merci d'avance,

Thomas

**Comment by bzg** [comment]
Hello ! La communication de la DINUM ne publie plus le logo en version inclusive, désolé.

**Comment by oncletom** [comment]
Dac, dommage. Je ferai avec le logo existant !

Merci pour ta réponse :-)
