### ISSUE TITLE
Résoudre bug bouton "découvrir les autres défis"

### ISSUE THREAD

**Issue by MathildeBras** [entrepreneur-interet-general/site-eig#45]
Actuellement
- quand on clique sur "découvrir les autres défis" des défis EIG3, cela renvoie vers la page de l'AAC eig3 : nickel
- quand on clique sur "découvrir les autres défis" d'autres défis (EIG1 ou EIG2), cela renvoie aussi vers la page de l'AAC eig3, ce qui est moins logique.

Est-ce possible de décorréler les 2 ?

**Comment by bzg** [comment]
Oui, c'est fait dans https://github.com/entrepreneur-interet-general/site-eig/commit/2a76ce531348d641cd848755b3d3fbcf98aed232

Pour les défis EIG1 et EIG2, "Voir les autres défis" pointe vers la page des défis EIG1 et EIG2.

Pour les défis EIG3, le même lien pointe vers les défis EIG3.
