### ISSUE TITLE
Pas prioritaire : tester l'insertion de lien dans la partie "piliers" de la page d'accueil

### ISSUE THREAD

**Issue by MathildeBras** [entrepreneur-interet-general/site-eig#48]
Review de LL : pouvoir cliquer sur "le défi", "le mentor", "l'EIG" et faire renvoyer à des pages du site.

**Comment by bzg** [comment]
Je viens de tester, on peut ajouter des liens: vers quelles pages doivent pointer "Le défi", "Le mentor" et "l'EIG" ?  Idéalement, ce serait une partie de notre glossaire (la page `glossaire.org` sur github), non ?

**Comment by bzg** [comment]
J'ai ajouté des liens vers les pages `defis.html` et `communaute`. Quand nous aurons des entrées dans le glossaire et ce même glossaire sur le site, nous pourrons mettre à jour.
