### ISSUE TITLE
Pas prioritaire : page défis faire migrer les présentations de slideshare à speakerdeck

### ISSUE THREAD

**Issue by MathildeBras** [entrepreneur-interet-general/site-eig#50]

**Comment by MathildeBras** [comment]
Fait pour les défis EIG2. Il reste encore des présentations sur slideshare et d'autres sur le serveurs (ex : présentation à l'Ukraine and co, présentations EIG1) à faire migrer.

**Comment by bzg** [comment]
- [ ] Défis EIG 1 (?)
- [x] Défis EIG 2
- [ ] Présentations des défis EIG 3
- [ ] Autres présentations EIG (Ukraine, etc.)

**Comment by bzg** [comment]
Aucune présentation slideshare n'est mentionnée sur le site. Je note la tâche en interne comme une tâche EIG3 en général, c'est mieux là que comme tâche "site web".
