### ISSUE TITLE
Footer - se conformer à la charte internet de l'Etat

### ISSUE THREAD

**Issue by MathildeBras** [entrepreneur-interet-general/site-eig#58]
Le pied de page doit faire figurer des liens vers les pages suivantes :
• page « contact » ;
• plan du site (sitemap) ;
• mentions légales ;
• page « accessibilité » : il est fortement recommandé de disposer
d’une page dédiée à l’accessibilité qui donne accès à votre déclaration
de conformité. À défaut, il est obligatoire d’intégrer les informations
réglementaires aux mentions légales ;

Le pied de page doit faire apparaître les liens ou les logos de :
• www . legifrance . gouv . fr
• www . service - public . fr
• www . gouvernement . fr
• www . data . gouv . fr

**Comment by bzg** [comment]
Résolu.
