### ISSUE TITLE
Page contact ?

### ISSUE THREAD

**Issue by MathildeBras** [entrepreneur-interet-general/site-eig#59]
Extrait charte internet de l'Etat :

Entrer en contact avec l’éditeur d’un site internet fait partie des bonnes pratiques du web. Dans
le cas de l’administration, il s’agit d’un droit de l’usager.

En effet, toutes les administrations (services de l’État, mairies, organismes de service public, etc.)
peuvent être saisies par voie électronique (SVE). Il s’agit de l’ordonnance du 6 novembre 2014 et
de son décret d’application sur la simplification des relations entre l’administration et les citoyens.
Ces mesures sont effectives depuis le 7 novembre 2015 pour l’État et ses établissements publics.

Sauf exceptions, après s’être identifié auprès de l’administration, l’usager peut :
- adresser par voie électronique toute demande, déclaration, document ou information à l’administration ;
- et/ou répondre à l’administration par cette voie, sans que le service concerné ne puisse lui demander de répéter ou confirmer sa saisine par une autre voie qui ne serait pas dématérialisée.

Lorsque l’administration a développé une démarche en ligne, elle n’est pas obligée de prendre
en compte la démarche initiée via le formulaire de contact. Elle réoriente alors l’usager vers la
démarche en ligne.

L’utilisation d’un formulaire comme l'un des moyens de contact est obligatoire,
sauf problématique justifiée. Si le volume de questions posées est important
et les sujets variés, il faut proposer une présélection des sujets de questions
posées afin de mettre en place un aiguillage des messages vers le(s) service(s)
compétent(s). Les adresses électroniques cliquables (attribut « mailto ») sont
interdites pour des raisons de sécurité et de compatibilité avec le poste de
travail de l’utilisateur sur l’ensemble des pages du site. Les établissements
disposant d’un accueil ouvert au public doivent fournir dans la page « contact »
un lien vers les horaires d’ouverture et le plan d’accès à l’établissement.

**Comment by bzg** [comment]
C'est fait !
