### ISSUE TITLE
Mettre à jour les liens vers les défis 2019 dans les pages "communauté"

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/site-eig#65]
Dans le répertoire `https://github.com/entrepreneur-interet-general/site-eig/tree/master/_communaute`, les liens vers les défis 2019 ne sont plus à jour depuis que nous avons renommé les URLs.

Cc @milkosofi pour suivi.

**Comment by MathildeBras** [comment]
je prends si vous voulez 


Le Mardi 4 Septembre 2018 08:38 CEST, Bastien <notifications@github.com> a écrit:
