### ISSUE TITLE
Ajouter les biographies des EIG et mentors de la première année

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/site-eig#7]

**Comment by MathildeBras** [comment]
EIG Ok, mentors non.

**Comment by bzg** [comment]
Ping @milkosofi

**Comment by bzg** [comment]
Fait pour les EIGs, pas encore pour les mentors.

**Comment by bzg** [comment]
@milkosofi pour voir s'il y a des choses qu'on peut ajouter dans les prochaines semaines.

**Comment by bzg** [comment]
J'avais mal lu : si c'est fait pour les EIG et qu'on n'a besoin de rien faire pour les mentors EIG 1, je ferme.
