### ISSUE TITLE
Menu décalé

### ISSUE THREAD

**Issue by Vict0rSch** [entrepreneur-interet-general/site-eig#70]
![Menu décalé](https://i.imgur.com/GpYsRvj.jpg)

Sur Mac + Chrome

**Comment by bzg** [comment]
Merci !  Est-ce que tu peux réessayer après https://github.com/entrepreneur-interet-general/site-eig/commit/f5c2563ec50810eb34fe74975b07a2fb9c7d2ca8 ?
