### ISSUE TITLE
Taille des photos sur le blog

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/site-eig#74]
Actuellement, les photos sont gigantesques, au moins sur laptop.

Pas bloquant, mais étonnant.

https://entrepreneur-interet-general.etalab.gouv.fr/blog/2018/06/11/travailler-avec-des-donnees-d-exception.html
<img width="1228" alt="screen shot 2018-09-12 at 21 41 39" src="https://user-images.githubusercontent.com/295709/45449151-ab6a6a00-b6d4-11e8-80ac-e83fa53bdba8.png">

**Comment by bzg** [comment]
PR welcome dans `style.css`, il faut garder le centrage de l'image et la légende juste en dessous.  Je dirais que 80% au lieu de 100% devrait être bon.

**Comment by bzg** [comment]
J'ai corrigé, ça devrait être mieux.
