### ISSUE TITLE
Uniformer taille police FAQ

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/site-eig#76]
Pages concernées : 
- https://github.com/entrepreneur-interet-general/site-eig/blob/master/faq-administrations.html
- https://github.com/entrepreneur-interet-general/site-eig/blob/master/faq-eig.html

Il y a une différence de balises entre div et h3.

Désolé @bzg je n'ai pas le temps de faire une PR ce soir...

**Comment by bzg** [comment]
Fait dans https://github.com/entrepreneur-interet-general/site-eig/commit/587ead98ec1c2d8ad42d3309abf8f90028ad2e6f et https://github.com/entrepreneur-interet-general/site-eig/commit/2e3327a7bf262a73e31e8f0f74c827e26fa670a5 - merci d'avoir détecté cet oubli !
