### ISSUE TITLE
Mentionner le télétravail

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/site-eig#77]
C'est une question importante pour beaucoup de candidats je pense

**Comment by bzg** [comment]
Oui, c'est une question qui est revenue par mail plusieurs fois.

Je propose cette formulation: 

« Q: Puis-je participer à mon défi en télétravail, complètement ou partiellement ?
R: Le possibilité de travailler à distance varie selon les administrations. La plupart le permettent et l'encadrent, mais il faudra que vous posiez la question aux mentors lors des entretiens. Gardez à l'esprit que les défis sont des défis d'_équipe_ et que la proximité entre les EIG est un facteur de réussite important. »

@MathildeBras @soizicpenicaud Go ?

**Comment by bzg** [comment]
Fait dans https://github.com/entrepreneur-interet-general/site-eig/commit/8c4c02971d207d019436577ac28dbd1039d2fd34
