### ISSUE TITLE
Renseigner les lieux de travail pour les défis 2019

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/site-eig#78]
Présents sur certains défis, absents sur d'autres

**Comment by bzg** [comment]
Pas sûr de voir ce que tu veux dire: toutes les administrations proposent des bureaux, non ?  Servons-nous de l'issue pour aboutir à la formulation définitive.

**Comment by MathildeBras** [comment]
À la fin de la description des profils d’eig recherches, certains ont dit ou se situait les bureaux (Montreuil, La Défense and co).
Ces infos sont dans les dossiers de l’appel à projets. 
Mathilde 

Envoyé de mon iPhone

**Comment by bzg** [comment]
OK, gardons l'issue ouverte le temps de voir si toutes les infos des dossiers sont bien publiques sur le site.

**Comment by bzg** [comment]
Voir la question "Où travaillent les EIG ?" dans la FAQ Entrepreneur du site: la possibilité du télétravail est indiquée, et il faudra veiller pour EIG 3 à faire en sorte que les lieux de travail soient mieux renseignés.
