### ISSUE TITLE
Conserver les liens historiques du blog

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/site-eig#82]
Semblable à #81.

Ancien lien : https://entrepreneur-interet-general.etalab.gouv.fr/posts/2018/06/11/travailler-avec-des-donnees-d-exception/
Nouveau : https://entrepreneur-interet-general.etalab.gouv.fr/blog/2018/06/11/travailler-avec-des-donnees-d-exception.html

Faire une 301 serait idéal

**Comment by bzg** [comment]
J'ai fait la redirection 301 aussi ici, merci !
