### ISSUE TITLE
Licence? Open source?

### ISSUE THREAD

**Issue by JeromeMartinez** [entrepreneur-interet-general/site-eig#83]
La FAQ dit 

> De plus, l’obligation, sauf dérogation, de verser les développements réalisés en open source rend leur maintien possible par tous.

Mais (la plupart) les repos GitHub (dont celui-ci) disent "rien à faire de l'open source vous n'avez le droit à rien" (licence par défaut selon la loi française et d'autres, quand il n'y a aucune indication sur la licence).
Donc 0% open source.

Quelle est la licence de ce repo?

Il serait peut-être utile d'ajouter un fichier de licence (et une "best practice" est de l'indiquer aussi dans le readme) que pour les gens sachent explicitement ce qu'ils ont le droit de faire et ne pas faire avec ce code, et/ou changer la FAQ si l'open source n'a pas d'importance en pratique pour EIG dans son ensemble et que c'est à la bonne volonté de chaque projet (si il en avait de manière générale, aucun des repos ne serait toléré sans licence open source, et ce dès le premier commit).

**Comment by bzg** [comment]
Bonjour Jérôme,

> Quelle est la licence de ce repo?

C'est la licence Ouverte, j'ai corrigé cet oubli dans https://github.com/entrepreneur-interet-general/site-eig/commit/2cfebc71173bbea31b0c83c5756611322d6f825c

Pour ce qui est des licences des autres dépôts du compte d'organisation EIG, c'est un autre problème, à traiter pour chaque dépôt, mais en général, tous devraient indiquer une licence libre.
