### ISSUE TITLE
Important : réparer le lien vers le mémo en anglais

### ISSUE THREAD

**Issue by soizicpenicaud** [entrepreneur-interet-general/site-eig#94]
Le lien "https://entrepreneur-interet-general.etalab.gouv.fr/assets/Public-Interest-Entrepreneurs-EN-memo.pdf" renvoie vers une erreur 404.

**Comment by bzg** [comment]
C'est corrigé.  Le lien est désormais https://entrepreneur-interet-general.etalab.gouv.fr/assets/Public-Interest-Entrepreneurs-EN-memo.pdf
