### ISSUE TITLE
« Je candidate » se dit « Je postule » ?

### ISSUE THREAD

**Issue by Antoine-H** [entrepreneur-interet-general/site-eig#96]
Bonjour,

J'ai remarqué la mention « Je candidate ! » sur la page [defi2019.html](https://github.com/entrepreneur-interet-general/site-eig/blob/44eabcd895f2986d014387ee78616361fd8d348d/_layouts/defi2019.html).

[L'académie française semble préférer l'emploi du verbe « postuler »](http://www.academie-francaise.fr/candidater).

Faut-il remplacer la mention « Je candidate ! » par « Je postule ! » ?

Bonne journée :),
Antoine

**Comment by bzg** [comment]
Bonjour,

j'ai corrigé en "Je pose ma candidature".

Merci d'avoir fait remonté ce problème !

**Comment by bzg** [comment]
Après discussion avec l'équipe, nous rétropédalons. Merci néanmoins pour l'information !
