### ISSUE TITLE
Mettre en valeur les réalisations des défis EI2

### ISSUE THREAD

**Issue by MathildeBras** [entrepreneur-interet-general/site-eig#97]
Dans les pages des défis et en top dans les réalisations.
Enjeu de capitalisation de la connaissance.

**Comment by bzg** [comment]
Je viens de compiler tout le contenu du fichier de suivi en `.csv`: lisible et téléchargeable [ici](https://github.com/entrepreneur-interet-general/eig-link/blob/master/data/suivi_compilation.csv).

On pourra faire un peu de spéléo!

**Comment by bzg** [comment]
Il y a aussi toutes les présentations des défis à mi-parcours sur https://speakerdeck.com/eig2018

**Comment by bzg** [comment]
Il y a aussi toutes les présentations des défis à mi-parcours sur https://speakerdeck.com/eig2018

**Comment by AntoineAugusti** [comment]
Fait dans Fait dans https://github.com/entrepreneur-interet-general/site-eig/pull/189
